DECLARE @NombreRuta VARCHAR(20)
SET @NombreRuta='SD100-02'

SELECT DISTINCT NombreRuta,
		CodCliente,
		Nombre,S.* 
		,i.ITEMDESC

FROM PalmComSync..GP_CLIENTEDIASRUTA G 
LEFT JOIN (
SELECT* FROM (SELECT CUSTNMBR,
		SERLNMBR'SERIE',
		ITEMNMBR'ACTIVOS',
		REFRENCE,
		INSTDTE'FECHAINSTALACION',
		USRDEF05'CAPACIDAD',
		USRDEF04'MARCA',
		CASE WHEN ITEMNMBR LIKE 'A%' THEN 'ANAQUEL'
						WHEN ITEMNMBR LIKE 'BB%' THEN 'BEBEDERO'
						WHEN ITEMNMBR LIKE 'N%' THEN 'NEVERAS' 
						WHEN ITEMNMBR LIKE 'E%'  THEN 'EXHIBIDOR'
						WHEN ITEMNMBR LIKE '%PURA%' THEN 'RACK-PURA'
						WHEN ITEMNMBR LIKE '%KEEPRITE SC-288LP%' THEN 'EXHIBIDOR'
						ELSE 'OTROS' 
						END'CATEGORIA'
		
FROM GPHN..SVC00300 
WHERE Version<>'') E 
/*WHERE 
E.CATEGORIA LIKE CASE WHEN @NombreRuta Like '__10%' THEN '%[^ANAQUEL,BEBEDERO]'
		              WHEN @NombreRuta Like '__30%' THEN '%[^NEVERAS]'
					  WHEN @NombreRuta Like '__90%' THEN '%PURA%'	 
				   -- WHEN @NombreRuta Like '__90%' THEN '%PURA%'
				      ELSE '%[^]'
					  END*/
) S ON G.CodCliente=S.CUSTNMBR LEFT JOIN  GPHN..IV00101 i ON S.ACTIVOS=i.ITEMNMBR
WHERE CodCliente IN (



SELECT CodCliente

FROM PalmComSync..GP_CLIENTEDIASRUTA 
WHERE  NombreRuta IN ('BDA300-05')   )AND NombreRuta='BDA300-05'

ORDER BY CodCliente

SELECT     *
FROM         RM00101
 


SELECT CUSTNMBR Codigo,
		CUSTNAME Nombre,
		NombreRuta Ruta,
		ADDRESS1 Direccion1,
		ADDRESS2 Direccion2,
		ADDRESS3 Direccion3,
		CITY Ciudad,
		STATE Estado,
		PHONE1 Telefono 
FROM PalmComSync..GP_CLIENTEDIASRUTA cr INNER JOIN RM00101 r ON cr.CodCliente=r.CUSTNMBR
WHERE cr.NombreRuta='BDA300-05'
GROUP BY CUSTNMBR  ,
		CUSTNAME  ,
		NombreRuta  ,
		ADDRESS1  ,
		ADDRESS2  ,
		ADDRESS3  ,
		CITY  ,
		STATE  ,
		PHONE1
		ORDER BY CUSTNMBR
		
		
	SELECT CodCliente,NombreRuta FROM PalmComSync..GP_CLIENTEDIASRUTA
	WHERE CodCliente IN (	
		SELECT CodCliente

FROM PalmComSync..GP_CLIENTEDIASRUTA 
WHERE  NombreRuta IN ('BDA300-05')) AND NombreRuta<>'BDA300-05'
GROUP BY CodCliente,NombreRuta
ORDER BY CodCliente


SELECT CUSTNMBR, SERLNMBR
FROM GPHN..SVC00300 
WHERE CUSTNMBR IN (SELECT CodCliente

FROM PalmComSync..GP_CLIENTEDIASRUTA 
WHERE  NombreRuta IN ('BA300-14')) AND Version<>''
ORDER  BY CUSTNMBR

SELECT * FROM PalmComSync..GP_RUTA
WHERE NombreRuta='BA300-14'
SELECT *

FROM PalmComSync..GP_CLIENTEDIASRUTA 
WHERE  NombreRuta IN ('BA300-14')


