 SELECT a.CUSTNMBR,a.CATEGORIA,SUM(CANTIDAD)'CANTIDAD' 
 FROM (
  SELECT CUSTNMBR,
		
		CASE WHEN ITEMNMBR LIKE 'A%' THEN 'ANAQUEL'
						WHEN ITEMNMBR LIKE 'BB%' THEN 'BEBEDERO'
						WHEN ITEMNMBR LIKE 'N%' THEN 'NEVERAS' 
						WHEN ITEMNMBR LIKE 'E%'  THEN 'EXHIBIDOR'
						WHEN ITEMNMBR LIKE '%PURA%' THEN 'RACK-PURA'
						WHEN ITEMNMBR LIKE '%KEEPRITE SC-288LP%' THEN 'EXHIBIDOR'
						ELSE 'OTROS' 
						END'CATEGORIA',
						COUNT(ITEMNMBR)'CANTIDAD'
						
		
FROM GPHN..SVC00300  
WHERE Version<>'' AND CUSTNMBR IN (  SELECT  v.CUSTNMBR, V.ITEMNMBR, V.XTNDPRCE FROM GPHN..vw_VentasGP1 v INNER JOIN GPHN..RM00101 r ON v.CUSTNMBR=r.CUSTNMBR
  WHERE DOCDATE BETWEEN '20150601' AND '20150831' AND v.LOCNCODE='SANISIDRO' AND V.CUSTNMBR='32532'
  GROUP BY CUSTCLAS,v.CUSTNMBR,V.CUSTNAME,V.ITEMNMBR
  )
GROUP BY CUSTNMBR,ITEMNMBR ) a

GROUP BY a.CUSTNMBR,a.CATEGORIA
ORDER BY a.CUSTNMBR
 
 
 SELECT  v.CUSTNMBR,
         V.ITEMNMBR,  
         CASE WHEN iv.UOMPRICE IS NULL AND v.ITEMNMBR LIKE 'PT1%' THEN 40
              WHEN iv.UOMPRICE IS NULL AND v.ITEMNMBR LIKE 'PT3%' THEN 44
              WHEN iv.UOMPRICE IS NULL AND v.ITEMNMBR LIKE 'PT4%' THEN 118
              WHEN iv.UOMPRICE IS NULL AND v.ITEMNMBR LIKE 'PT6%' THEN 28
              WHEN iv.UOMPRICE IS NULL AND v.ITEMNMBR LIKE 'PT9%' THEN 37.75
              ELSE iv.UOMPRICE  END'PRECIO'
  FROM GPHN..vw_VentasGP1 v 
 INNER JOIN GPHN..RM00101 r ON v.CUSTNMBR=r.CUSTNMBR
 LEFT JOIN IV00108 iv ON r.PRCLEVEL=iv.PRCLEVEL AND v.ITEMNMBR=iv.ITEMNMBR
 WHERE  DOCDATE BETWEEN '20150601' AND '20150831' AND v.LOCNCODE='SANISIDRO' --AND V.CUSTNMBR='22026'
 GROUP BY  v.CUSTNMBR,V.ITEMNMBR,iv.UOMPRICE 

/*
SELECT * FROM IV00108
WHERE PRCLEVEL ='PRECIO_BAS' AND ITEMNMBR LIKE 'PT9%'*/