
SELECT * FROM RM00101
WHERE PRCLEVEL <>'' 
AND CUSTNMBR IN (SELECT CUSTNMBR FROM vw_VentasGP WHERE LOCNCODE='SANISIDRO' AND DOCDATE BETWEEN '20130101' AND '20150601' )


SELECT * FROM IV00108
WHERE PRCLEVEL IN (SELECT PRCLEVEL FROM import..NIVELDEPRECIOPARA5) 
AND ITEMNMBR ='PT100'


--- ACTUALIZAR BOTELLON 2 Pesos SAN ISIDRO 

SELECT * FROM IV00108
WHERE PRCLEVEL IN (SELECT PRCLEVEL FROM RM00101
WHERE PRCLEVEL <>'' 
AND CUSTNMBR IN (SELECT CUSTNMBR FROM vw_VentasGP WHERE LOCNCODE='SANISIDRO' AND DOCDATE BETWEEN '20130101' AND '20150601' )) 
AND ITEMNMBR ='PT100'



-----BATELLITAS 2 Pesos
SELECT * FROM PalmComSync..OUT_PRODUCTO

WHERE PALMID IN (
SELECT PALMID FROM PalmComSync..OUT_CONFIG
WHERE PALMID LIKE '%GEA%' AND IDVENDEDOR<>'' AND DIRECCION LIKE '%ROMANA%') AND CODPROD = 'PT901' --AND PRECMAX=37

--- Falditos 1


SELECT * FROM PalmComSync..OUT_PRODUCTO
WHERE PALMID IN (
SELECT PALMID FROM PalmComSync..OUT_CONFIG
WHERE PALMID LIKE '%GEA%' AND IDVENDEDOR<>'' AND DIRECCION LIKE '%SAN%') AND CODPROD = 'PT600'

--- BOTELLON EN LA PALM 2 

SELECT * FROM PalmComSync..OUT_PRODUCTO
WHERE PALMID IN (
SELECT PALMID FROM PalmComSync..OUT_CONFIG
WHERE PALMID LIKE '%GEA%' AND IDVENDEDOR<>'' AND DIRECCION LIKE '%SAN%') AND CODPROD = 'PT300'






SELECT * FROM GPHN..RM00101
WHERE CUSTNMBR IN ('10479',      
'10480 ',     
'11239',      
'11442',      
'17758',      
'18027',      
'18673',      
'22081',      
'29239',      
'31211 ',     
'32528 ',     
'32775',      
'32865',      
'33073',      
'38582'      
)




SELECT s.*, R.PRCLEVEL   FROM import..[AUMENTOHIELO5] s INNER JOIN GPHN..RM00101 R ON CONVERT(VARCHAR(5),s.cod)=R.CUSTNMBR

SELECT * FROM GPHN..RM00101
WHERE PRCLEVEL IN (
SELECT PRCLEVEL  FROM import..NIVELDEPRECIOPARA5)



SELECT * FROM PalmComSync..OUT_PRODUCTO
WHERE PALMID IN (
'GEA075')


SELECT * FROM SITGPIntegration..RelacionConduce
WHERE NoDocumento='000000000127346'