USE  GPHN
--1) ======Buscar secuencia de la Factura para fines de saltos
SELECT * FROM (
SELECT DOCID,SOPNUMBE,DOCDATE 
FROM GPHN..SOP30200


UNION ALL

SELECT DOCID,SOPNUMBE,DOCDATE
FROM GPHN..SOP10100
) A
WHERE A.DOCDATE BETWEEN '20160701' AND '20160731' AND DOCID NOT IN ( 'PALMFACTURA','CONDUCE','CALLS SERVICE','MANUAL','PEDIDO')
ORDER BY SOPNUMBE

 ---------------------
 
 --===================
--2) VERIFICAR QUE NO HAYA FACTURA ENGANCHADA

SELECT * FROM GPHN..SOP10100
WHERE DOCDATE='1900-01-01 00:00:00.000' 

/*
		SI aparece factura debe correr el mantenimiento de facturas en GP


*/
--=============================================
 
 
 
 
 --3)===== BUSCAR SALTO ARCHIVO
SELECT * FROM import..[SALTOSJULIO2016A]
WHERE SALTOS  NOT IN (
SELECT SOPNUMBE FROM (
SELECT DOCID,SOPNUMBE,DOCDATE 
FROM GPHN..SOP30200 



UNION ALL

SELECT DOCID,SOPNUMBE,DOCDATE
FROM GPHN..SOP10100
 
) A
WHERE A.DOCDATE<>'1900-01-01 00:00:00.000'

)
