SELECT  B.ASSETID, B.EXTASSETDESC, B.ASSETCLASSID, A.YTDDEPRAMT,
 A.FAPERIOD, D.ACTNUMBR_2, d.ACTDESCR,  E.ACTNUMBR_2, E.ACTDESCR FROM FA41900 A JOIN FA00100 B 
ON A.ASSETINDEX  = B.ASSETINDEX 
JOIN FA00400
 C ON A.ASSETINDEX = C.ASSETINDEX JOIN 
GL00100 D ON C.ASSETCOSTACCTINDX = D.ACTINDX  JOIN GL00100 E ON C.DEPREXPACCTINDX = E.ACTINDX  
AND A.FAPERIOD = 6 and A.FAYEAR = 2017 and USERID = 'carlos.olmos'


--select * from FA00400 