
SELECT A.CUSTNMBR, A.CUSTNAME, A.CUSTCLAS, A.CPRCSTNM, A.CNTCPRSN, A.STMTNAME, A.SHRTNAME, A.ADRSCODE, A.ADDRESS1, A.ADDRESS2, A.ADDRESS3, A.COUNTRY, A.CITY, A.STATE, A.PHONE1, A.PHONE2, A.PHONE3, A.FAX, A.PRBTADCD, A.PYMTRMID, A.PRCLEVEL, A.COMMENT1, A.COMMENT2, A.USERDEF1, A.USERDEF2, A.TXRGNNUM, A.SALSTERR, A.INACTIVE, A.HOLD, A.CREATDDT, A.MODIFDT, b.SERLNMBR, b.ITEMNMBR, b.REFRENCE, b.Version, b.SRLSTAT, b.INSTDTE, b.OFFID, b.SVCAREA, b.USERDEF1, b.USERDEF2, b.USRDEF03, b.USRDEF04,b.USRDEF05   FROM RM00101 A left JOIN SVC00300 B
on a.CUSTNMBR = b.CUSTNMBR
WHERE a.CUSTNMBR IN (SELECT CUSTNMBR  FROM SOP10100 where  LOCNCODE = 'romana' AND docdate < '2016.08.31'  UNION ALL SELECT CUSTNMBR FROM SOP30200
  where  LOCNCODE = 'romana' AND docdate < '2016.08.31' )
  order by a.CUSTNMBR
  
  
  
  ---obtener fecha ultima factura---
  select a.CUSTNMBR, MAX(a.DOCDATE) from SOP30200 a  
group by CUSTNMBR
union all select b.CUSTNMBR, MAX(b.DOCDATE) from SOP10100 b
group by CUSTNMBR
  

  
  