---use gphn

select A.CUSTNMBR AS CODIGO, a.RMDTYPAL, B.CUSTNAME AS NOMBRE, A.CPRCSTNM AS CORPORACION, A.DOCNUMBR AS DOCUMENTO, A.DOCDATE AS FECHA_DOCUMENTO, C.DATE1 AS FECHA_APP, A.DINVPDOF AS FECHA_APLICACION, A.ORTRXAMT AS MOTO_TOTAL, A.CURTRXAM AS MONTO_TRX_ACTUAL FROM RM20101 A inner JOIN RM00101 B 
ON A.CUSTNMBR = B.CUSTNMBR JOIN RM20201 C ON A.DOCNUMBR = C.APTODCNM
where CASHAMNT = 0 AND DOCDATE < '2011.01.01' and RMDTYPAL between '1' and '3'   ---AND DATE1 > '2007.12.31' and RMDTYPAL between '1' and '3'  
order by a.RMDTYPAL

---use gphn

select sum(CURTRXAM) As MOTO_TOTAL FROM RM20101 
where CASHAMNT = 0 and DOCDATE < '2011.01.01'   and RMDTYPAL between  1 and 3
order by DOCDATE

SELECT * FROM RM20201

select A.CUSTNMBR AS CODIGO, a.RMDTYPAL, B.CUSTNAME AS NOMBRE, A.CPRCSTNM AS CORPORACION, A.DOCNUMBR AS DOCUMENTO, A.DOCDATE AS FECHA_DOCUMENTO, C.DATE1 AS FECHA_APP, A.DINVPDOF AS FECHA_APLICACION, C.APTODCDT, A.ORTRXAMT AS MOTO_TOTAL, A.CURTRXAM AS MONTO_TRX_ACTUAL, c.APPTOAMT as MONTO_APLICADO FROM RM20101 A LEFT JOIN RM00101 B 
ON A.CUSTNMBR = B.CUSTNMBR INNER JOIN RM20201 C ON A.DOCNUMBR = C.APTODCNM
where CASHAMNT = 0 AND DOCDATE < '2011.01.01' and RMDTYPAL between '1' and '3' --AND DATE1 > '2010.12.31' and RMDTYPAL between '1' and '3'  
order by C.APTODCDT


select A.CUSTNMBR AS CODIGO, a.RMDTYPAL, B.CUSTNAME AS NOMBRE, A.CPRCSTNM AS CORPORACION, A.DOCNUMBR AS DOCUMENTO, A.DOCDATE AS FECHA_DOCUMENTO, C.DATE1 AS FECHA_APP, A.DINVPDOF AS FECHA_APLICACION, A.ORTRXAMT AS MOTO_TOTAL, A.CURTRXAM AS MONTO_TRX_ACTUAL, c.APPTOAMT as MONTO_APLICADO FROM RM20101 A INNER JOIN RM00101 B 
ON A.CUSTNMBR = B.CUSTNMBR INNER JOIN RM20201 C ON A.DOCNUMBR = C.APTODCNM
where CASHAMNT = 0 AND DOCDATE < '2011.01.01' AND DATE1 > '2010.12.31' and RMDTYPAL between '1' and '3'  
--order by a.RMDTYPAL

SELECT CUSTNMBR, DATE1, GLPOSTDT, APTODCNM, APTODCDT, ApplyToGLPostDate, APPTOAMT FROM RM20201
WHERE APFRDCNM = '8925-212950'

select sum(ortrxamt) from rm20101
where DOCDATE between '2010.01.01' and '2010.12.31' and CASHAMNT = 0 and RMDTYPAL in (1,3)

