
select *   FROM DYNAMICS..ACTIVITY
select *   FROM DYNAMICS..SY00800
select *   FROM DYNAMICS..SY00801
select *   FROM TEMPDB..DEX_LOCK
select *   FROM TEMPDB..DEX_SESSION

/*
delete   FROM DYNAMICS..ACTIVITY
delete  FROM DYNAMICS..SY00800
delete   FROM DYNAMICS..SY00801
delete   FROM TEMPDB..DEX_LOCK
delete   FROM TEMPDB..DEX_SESSION
*/