DECLARE @IFECHA DATETIME, @AFECHA DATETIME

SET @IFECHA='20130101'
SET @AFECHA='20131231'

SELECT a.LOCALIDAD,a.DEPARTAMENTO,a.ACTDESCR,a.ITEMNMBR,a.ITEMDESC,SUM(a.TRXQTY)'TRXQTY',(SUM(a.UNITCOST)/COUNT(a.ITEMNMBR))'UNITCOST',((SUM(a.UNITCOST)/COUNT(a.ITEMNMBR))*SUM(a.TRXQTY))'TOTAL' FROM (
SELECT DISTINCT iv1.IVDOCNBR,
                iv.DOCDATE,
                l1.ITEMNMBR,
                ivi.ITEMDESC,
                l1.TRXQTY,
                l1.UNITCOST,
               aaTrxDimCode 'DEPARTAMENTO',
                l1.LOCALIDAD,
             
               
                l1.ACTDESCR 
FROM IV10000 iv 
INNER JOIN IV10001 iv1 ON iv.IVDOCNBR=iv1.IVDOCNBR 
INNER JOIN AAG20000 AAG0 ON iv.IVDOCNBR=AAG0.DOCNUMBR
INNER JOIN AAG20003 AAG1 ON  AAG0.aaSubLedgerHdrID=AAG1.aaSubLedgerHdrID
INNER JOIN AAG00401 AAG4 ON  AAG1.aaTrxDimID=AAG4.aaTrxDimID AND AAG1.aaTrxCodeID=AAG4.aaTrxDimCodeID
INNER JOIN GL00100 GL ON iv1.IVIVOFIX=GL.ACTINDX
INNER JOIN (
SELECT DISTINCT iv1.IVDOCNBR,
                iv.DOCDATE,
                ITEMNMBR,
                TRXQTY,
                UNITCOST,
              
                 aaTrxDimCode 'LOCALIDAD',
               
               
               
                ACTDESCR 
FROM IV10000 iv 
INNER JOIN IV10001 iv1 ON iv.IVDOCNBR=iv1.IVDOCNBR 
INNER JOIN AAG20000 AAG0 ON iv.IVDOCNBR=AAG0.DOCNUMBR
INNER JOIN AAG20003 AAG1 ON  AAG0.aaSubLedgerHdrID=AAG1.aaSubLedgerHdrID
INNER JOIN AAG00401 AAG4 ON  AAG1.aaTrxDimID=AAG4.aaTrxDimID AND AAG1.aaTrxCodeID=AAG4.aaTrxDimCodeID
INNER JOIN GL00100 GL ON iv1.IVIVOFIX=GL.ACTINDX
WHERE iv1.IVDOCTYP=1 AND   AAG4.aaTrxDimID=3 AND iv.DOCDATE BETWEEN @IFECHA AND @AFECHA
GROUP BY iv1.IVDOCNBR,iv.DOCDATE,ITEMNMBR,TRXQTY,UNITCOST,AAG4.aaTrxDimID,AAG4.aaTrxDimCodeID,AAG4.aaTrxDimCode,ACTDESCR



) l1 ON l1.IVDOCNBR=iv.IVDOCNBR INNER JOIN IV00101 ivi ON l1.ITEMNMBR=ivi.ITEMNMBR
WHERE iv1.IVDOCTYP=1 AND  AAG4.aaTrxDimID=2 AND iv.DOCDATE BETWEEN @IFECHA AND @AFECHA
GROUP BY iv1.IVDOCNBR,iv.DOCDATE,l1.ITEMNMBR,l1.TRXQTY,l1.UNITCOST,AAG4.aaTrxDimID,AAG4.aaTrxDimCodeID,AAG4.aaTrxDimCode,l1.ACTDESCR
,l1.LOCALIDAD, ivi.ITEMDESC
-----------------------------------------------------
UNION ALL

SELECT DISTINCT iv1.DOCNUMBR,
                iv1.DOCDATE,
                l1.ITEMNMBR,
                ivi.ITEMDESC,
                l1.TRXQTY,
                l1.UNITCOST,
                 aaTrxDimCode 'DEPARTAMENTO',
                 l1.LOCALIDAD,
              
               
                l1.ACTDESCR 
FROM  IV30300 iv1 
INNER JOIN AAG20000 AAG0 ON iv1.DOCNUMBR=AAG0.DOCNUMBR
INNER JOIN AAG20003 AAG1 ON  AAG0.aaSubLedgerHdrID=AAG1.aaSubLedgerHdrID
INNER JOIN AAG00401 AAG4 ON  AAG1.aaTrxDimID=AAG4.aaTrxDimID AND AAG1.aaTrxCodeID=AAG4.aaTrxDimCodeID
INNER JOIN GL00100 GL ON iv1.IVIVOFIX=GL.ACTINDX
INNER JOIN (
SELECT DISTINCT iv1.DOCNUMBR,
                iv1.DOCDATE,
                ITEMNMBR,
                TRXQTY,
                UNITCOST,
              
                aaTrxDimCode 'LOCALIDAD',
               
               
               
                ACTDESCR 
FROM IV30300 iv1 
INNER JOIN AAG20000 AAG0 ON iv1.DOCNUMBR=AAG0.DOCNUMBR
INNER JOIN AAG20003 AAG1 ON  AAG0.aaSubLedgerHdrID=AAG1.aaSubLedgerHdrID
INNER JOIN AAG00401 AAG4 ON  AAG1.aaTrxDimID=AAG4.aaTrxDimID AND AAG1.aaTrxCodeID=AAG4.aaTrxDimCodeID
INNER JOIN GL00100 GL ON iv1.IVIVOFIX=GL.ACTINDX
WHERE iv1.DOCTYPE=1 AND   AAG4.aaTrxDimID=3 AND iv1.DOCDATE BETWEEN @IFECHA AND @AFECHA
GROUP BY iv1.DOCNUMBR,iv1.DOCDATE,ITEMNMBR,TRXQTY,UNITCOST,AAG4.aaTrxDimID,AAG4.aaTrxDimCodeID,AAG4.aaTrxDimCode,ACTDESCR



) l1 ON l1.DOCNUMBR=iv1.DOCNUMBR INNER JOIN IV00101 ivi ON l1.ITEMNMBR=ivi.ITEMNMBR
WHERE iv1.DOCTYPE=1  AND  AAG4.aaTrxDimID=2 AND iv1.DOCDATE BETWEEN @IFECHA AND @AFECHA
GROUP BY iv1.DOCNUMBR,iv1.DOCDATE,l1.ITEMNMBR,l1.TRXQTY,l1.UNITCOST,AAG4.aaTrxDimID,AAG4.aaTrxDimCodeID,AAG4.aaTrxDimCode,l1.ACTDESCR
,l1.LOCALIDAD,ivi.ITEMDESC

) a
GROUP BY a.LOCALIDAD,a.DEPARTAMENTO,a.ACTDESCR,a.ITEMNMBR,a.ITEMDESC
