SELECT * FROM PalmComSync..GP_CLIENTEDIASRUTA

SELECT Idvendedor,NombreVendedor, R.NombreRuta, SUM(CONVERT(INTEGER,Lunes))'Lunes',SUM(CONVERT(INTEGER,Martes))'Martes',SUM(CONVERT(INTEGER,Miercoles))'Miercoles',SUM(CONVERT(INTEGER,Jueves))'Jueves',SUM(CONVERT(INTEGER,Viernes))'Viernes',SUM(CONVERT(INTEGER,Sabado))'Sabado',SUM(CONVERT(INTEGER,Domingo))'Domingo' FROM PalmComSync..GP_RUTA R INNER JOIN PalmComSync..GP_CLIENTEDIASRUTA C ON R.NombreRuta=c.NombreRuta
GROUP BY Idvendedor,NombreVendedor, R.NombreRuta
ORDER BY IdVendedor





SELECT COUNT(CodCliente) FROM PalmComSync..GP_CLIENTEDIASRUTA
WHERE NombreRuta='SD100-23' AND Lunes=1


/*
SELECT B.CUSTNMBR,SUM(HIELO)'HIELO',SUM(BLOCK)'BLOCK',SUM(B.[1.5])'1.5',SUM(AGUA)'AGUA',SUM(BOTELLITA)'BOTELLITA',TIPO FROM (
SELECT CUSTNMBR, 
     
       CASE WHEN ITEMNMBR LIKE '%PT1%' 
       THEN SUM(QUANTITY)ELSE 0 END'HIELO', 
       
        CASE WHEN ITEMNMBR LIKE '%PT2%' --OR ITEMNMBR='PT201'
       THEN SUM(QUANTITY) ELSE 0 END'BLOCK',
       
        CASE WHEN ITEMNMBR LIKE '%PT3%' 
       THEN SUM(QUANTITY)ELSE 0 END'AGUA',
       
        CASE WHEN ITEMNMBR LIKE '%PT5%' --OR ITEMNMBR='PT504'
       THEN SUM(QUANTITY)ELSE 0 END'1.5',
       
        CASE WHEN ITEMNMBR LIKE '%PT4%' 
       THEN SUM(QUANTITY) ELSE 0 END'BOTELLITA',
       
        CASE WHEN ITEMNMBR LIKE '%PT9%' 
       THEN SUM(QUANTITY) ELSE 0 END'PURA',
       
      CASE WHEN DOCID='PALMFACTURA' OR DOCID= 'MANUAL'  THEN 'PALM'
           WHEN DOCID='A0100800101' OR DOCID='A0100800102' OR DOCID='A0100800114' THEN 'PLANTA'
           END 'TIPO'
       
       FROM import..clientepalmplanta1 c INNER JOIN GPHN..vw_VentasGP v ON CONVERT(VARCHAR(50),c.CodCliente)=CONVERT(VARCHAR(50),v.CUSTNMBR)
GROUP BY CUSTNMBR, ITEMNMBR, DOCID 
) AS B
GROUP BY CUSTNMBR,TIPO
ORDER BY CUSTNMBR
*/



SELECT  CodCliente FROM import..clientepalmplanta1
