DECLARE @fecha DATETIME
SET @fecha='20160704'

SELECT  CUSTNMBR,   APTODCNM, SUM(APFRMAPLYAMT+APFRMDISCTAKEN)MONTO
INTO ##APLIDOC FROM      dbo.RM20201
WHERE DATE1<=@fecha
GROUP BY CUSTNMBR,APTODCNM
 
 --DROP TABLE ##APLIDOC
 


SELECT
CM.CPRCSTNM 'CORPO',
CM.CUSTNMBR Cod_cliente, 
CM.CUSTNAME Nombre_cliente,
 sum(case
when  RM.RMDTYPAL < 7 AND DATEDIFF(d, RM.DOCDATE, @fecha) <31    THEN RM.ORTRXAMT-ISNULL(A.MONTO,0)
when  RM.RMDTYPAL > 6 AND RM.AGNGBUKT=1 then RM.CURTRXAM *-1
else 0
end) [menor_30],
 
sum(case
when RM.RMDTYPAL < 7 AND DATEDIFF(d, RM.DOCDATE,@fecha) between 31 and 60 then RM.ORTRXAMT-ISNULL(A.MONTO,0)
 
else 0
end) [31_a_60_Dias],
 
sum(case
when RM.RMDTYPAL < 7 AND DATEDIFF(d, RM.DOCDATE, @fecha) between 61 and 90 then RM.ORTRXAMT-ISNULL(A.MONTO,0)

else 0
end) [61_a_90_Dias],
 
sum(case
when RM.RMDTYPAL < 7 AND DATEDIFF(d, RM.DOCDATE, @fecha) between 91 and 120 then RM.ORTRXAMT-ISNULL(A.MONTO,0)

else 0
end) [91_a_120_Dias],
 sum(case
when RM.RMDTYPAL < 7 AND DATEDIFF(d, RM.DOCDATE, @fecha) between 121 and 150 then RM.ORTRXAMT-ISNULL(A.MONTO,0)
else 0
end) [121_a_150_Dias],

 sum(case
when RM.RMDTYPAL < 7 AND DATEDIFF(d, RM.DOCDATE, @fecha) between 151 and 180 then RM.ORTRXAMT-ISNULL(A.MONTO,0)
else 0
end) [151_a_180_Dias],

 sum(case
when RM.RMDTYPAL < 7 AND DATEDIFF(d, RM.DOCDATE, @fecha) >180 then RM.ORTRXAMT-ISNULL(A.MONTO,0)
else 0
end) [181_y_mas],

sum(case
when RM.RMDTYPAL < 7 then RM.ORTRXAMT-ISNULL(A.MONTO,0)
else RM.CURTRXAM * -1
end) Saldo ,
CM.CRLMTAMT Limite_actual,
CM.CUSTCLAS Clases,
ISNULL(CN.CRDTMGR,'') GESTORA,
CASE CM.SALSTERR WHEN 'GA-12' THEN 'BAVARO'
				 WHEN 'GA-13' THEN 'ROMANA'
				 WHEN 'GA-01' THEN 'SAN ISIDRO'
				 WHEN 'GA-02' THEN 'SAN ISIDRO'
				 WHEN 'GA-03' THEN 'SAN ISIDRO'
				 WHEN 'GA-04' THEN 'SAN ISIDRO'
				 WHEN 'GA-05' THEN 'SAN ISIDRO'
				 WHEN 'GA-06' THEN 'SAN ISIDRO'
				 WHEN 'GA-07' THEN 'SAN ISIDRO'
				 WHEN 'GA-08' THEN 'SAN ISIDRO'
				 WHEN 'GA-09' THEN 'SAN ISIDRO'
				 WHEN 'GA-10' THEN 'SAN ISIDRO'
				 WHEN 'GA-11' THEN 'SAN ISIDRO'
				 ELSE ' ' END Localidad,
CS.LASTPYDT Fecha_ultimo_pago,
CS.LPYMTAMT Ultimo_monto_pagado



FROM RM20101 RM LEFT JOIN ##APLIDOC A ON RM.DOCNUMBR=A.APTODCNM AND RM.CUSTNMBR=A.CUSTNMBR
inner join RM00101 CM
     on RM.CUSTNMBR = CM.CUSTNMBR
inner join RM00103 CS
     on RM.CUSTNMBR = CS.CUSTNMBR
LEFT JOIN CN00500 CN ON RM.CUSTNMBR=CN.CUSTNMBR
WHERE DOCDATE<=@fecha AND RM.CUSTNMBR='10479'  
AND VOIDSTTS=0 
AND CM.CUSTCLAS IN (@clase)  

group by CM.CPRCSTNM,CM.CUSTNMBR, CM.CUSTNAME, CM.PYMTRMID, CM.CUSTCLAS, 
         CM.CRLMTAMT, CS.LASTPYDT,CS.LPYMTAMT,CN.CRDTMGR,CM.SALSTERR

HAVING   sum(case
when RM.RMDTYPAL < 7 then RM.ORTRXAMT-ISNULL(A.MONTO,0)
else RM.CURTRXAM * -1
end) >0       
ORDER BY CM.CUSTNMBR