SELECT v.LOCNCODE,
		v.ITEMNMBR,
		v.ITEMDESC,
		'CANT_CRED'=SUM(CASE WHEN v.PYMTRCVD=v.DOCAMNT THEN 0 ELSE QUANTITY END),
		'VALOR_CRED'=SUM(CASE WHEN v.PYMTRCVD=v.DOCAMNT THEN 0 ELSE XTNDPRCE END),
		'CANT_CONT'=SUM(CASE WHEN v.PYMTRCVD=v.DOCAMNT THEN QUANTITY ELSE 0 END),
		'VALOR_CONT'=SUM(CASE WHEN v.PYMTRCVD=v.DOCAMNT THEN XTNDPRCE ELSE 0 END ),
		SUM(XTNDPRCE)'TOTAL_VALOR' ,
		SUM(QUANTITY)'TOTAL_CANT' 
		FROM  View_VentasGP2noGROUP   as v with(nolock)
WHERE v.DOCDATE BETWEEN '20150501' AND '20150531' 
GROUP BY v.LOCNCODE,v.ITEMNMBR,v.ITEMDESC



SELECT * FROM RM20101
WHERE DOCDATE BETWEEN '20150501' AND '20150531'  AND BCHSOURC IN ('XRM_Sales','RM_Sales') AND RMDTYPAL=1


---PT436
SELECT * FROM PalmComSync..OUT_PRODUCTO
WHERE CODPROD='PT436' --60

SELECT *   FROM  vw_VentasGP  WHERE 
 DOCDATE BETWEEN '20150501' AND '20150531' --AND  
--RTRIM(SOPNUMBE) NOT IN (SELECT RTRIM(ORIGNUMB) FROM SOP30200 WHERE SOPTYPE=4 )
ORDER BY SOPNUMBE



SELECT * FROM PalmComSync..GP_CLIENTEDIASRUTA
WHERE NombreRuta LIKE '%SD%'