SELECT * FROM IN_FACTURA_TEMP
WHERE PALMID='GEA015' AND FECHAFAC='20141123'



SELECT * FROM SITGPIntegration..TransaccionVenta
WHERE NoDocumento IN (SELECT FACNUM FROM IN_FACTURA_TEMP
WHERE PALMID='GEA015' AND FECHAFAC='20141123')


SELECT CUSTNMBR FROM GPHN..vw_ventasGP
WHERE LOCNCODE='BAVARO' AND DOCDATE <'20141116'

SELECT  CodCliente,NombCliente,IdClase,Inactivo,Suspendido,PersCont,Direccion1,Direccion2,Direccion3,FechaCreacion,UltFecFact FROM GPHN.dbo.VW_Clientes_CSR1
WHERE CodCliente IN (
SELECT CUSTNMBR FROM GPHN..vw_ventasGP
WHERE LOCNCODE='SANISIDRO' AND DOCDATE <='20141115')
GROUP BY CodCliente,NombCliente,IdClase,PersCont,Inactivo,Suspendido,Direccion1,Direccion2,Direccion3,FechaCreacion,UltFecFact


SELECT * FROM GPHN..vw_ventasGP
WHERE CUSTNMBR='13150'

SELECT [Número de cliente],[Nombre de cliente],[Dirección 1],[Dirección 2],[Ciudad],[Fecha de creación],[Fecha última transacción] FROM GPHN.dbo.CLIENTES
WHERE [Número de cliente] IN (SELECT CUSTNMBR FROM GPHN..vw_ventasGP
WHERE LOCNCODE='BAVARO' AND DOCDATE <'20141116')

SELECT * FROM GPHN.dbo.CLIENTES
WHERE [Número de cliente]='31460'

SELECT * FROM GPHN.dbo.VW_Clientes_CSR
WHERE CodCliente='31460'

SELECT * FROM GPHN..SVC00300
WHERE OFFID='BAV' AND CUSTNMBR <>'ALASKA' AND [Version] <>'' AND SVCAREA='GA-12'


SELECT G3.HSTYEAR'AÑO',(ACTNUMBR_1+ACTNUMBR_2+ACTNUMBR_3)'CUENTA',ACTDESCR AS 'DESCRIPCION',CRDTAMNT'CREDITO',DEBITAMT'DEBITO' FROM GL30000 G3 INNER JOIN GL00100 G1 ON G3.ACTINDX=G1.ACTINDX
WHERE G3.HSTYEAR='2012'

SELECT * FROM GL00100
       
SELECT A.SOURCDOC,
	   A.JRNENTRY,
       A.AÑO,
       A.Series,
       A.CUENTA,
       A.TRXDATE,
	   A.DESCRIPCION,
	   A.REFRENCE,
	   A.DSCRIPTN,
       A.ORCTRNUM,
       A.ORMSTRID,
       A.ORMSTRNM,
       A.ORDOCNUM,
       A.Tipo_transaccion,
       SUM(A.DEBITO)'DEBITO',
       SUM(A.CREDITO)'CREDITO',
      -- ISNULL(A.SALDO_INICIAL,0)'SALDO_INICIAL',
       A.ANULADO
FROM (
		SELECT G3.SOURCDOC,
		       JRNENTRY,
		       G3.HSTYEAR'AÑO',
		       G3.TRXDATE,
		       G3.ORCTRNUM,
		       G3.ORMSTRID,
		       G3.ORMSTRNM,
		       G3.ORDOCNUM,
		       (RTRIM(ACTNUMBR_1)+'-'+RTRIM(ACTNUMBR_2)+'-'+RTRIM(ACTNUMBR_3))'CUENTA',
		       ACTDESCR AS 'DESCRIPCION',
		       G3.DSCRIPTN,
		       G3.REFRENCE,
		       CASE VOIDED WHEN 0 THEN 'NO' ELSE 'SI' END'ANULADO',
		       CASE SERIES WHEN 1 THEN 'TODOS'
		                   WHEN 2 THEN 'FINANCIERO'
		                   WHEN 3 THEN 'VENTAS'
		                   WHEN 4 THEN 'COMPRAS'
		                   WHEN 5 THEN 'INVENTARIO'
		                   WHEN 6 THEN 'Nomina'
		                   WHEN 7 THEN 'Proyecto'
		                   WHEN 10 THEN 'Terceros'
		                   ELSE 'Otros' END 'Series',
		       CRDTAMNT'CREDITO',
		       DEBITAMT'DEBITO',
		      -- P.PERDBLNC'SALDO_INICIAL',
		       CASE WHEN SERIES=2 AND ORTRXTYP=0 THEN 'Entrada de Diario Financiero'
		            WHEN SERIES=2 AND ORTRXTYP=2 THEN 'Recibo de Transaccion Bancarias'
		            WHEN SERIES=2 AND ORTRXTYP=5 THEN 'Aumento de Ajuste T. Bancarias'
		            WHEN SERIES=2 AND ORTRXTYP=6 THEN 'Disminucion de Ajuste T. Bancarias'
		            WHEN SERIES=3 AND ORTRXTYP=1 THEN 'Factura'
		            WHEN SERIES=3 AND ORTRXTYP=3 THEN 'Factura'
		            WHEN SERIES=3 AND ORTRXTYP=4 THEN 'Factura'
		            WHEN SERIES=3 AND ORTRXTYP=7 THEN 'Nota de Credito'
		            WHEN SERIES=3 AND ORTRXTYP=8 THEN 'Aplicacion a Documento por pagar'
		            WHEN SERIES=3 AND ORTRXTYP=9 THEN 'Cobros'
		            WHEN SERIES=4 AND ORTRXTYP=0 THEN 'Compras otros'
		            WHEN SERIES=4 AND ORTRXTYP=1 THEN 'Factura de Compras'
		            WHEN SERIES=4 AND ORTRXTYP=2 THEN 'Factura de Compras'
		            WHEN SERIES=4 AND ORTRXTYP=3 THEN 'Nota de Debito de Compras'
		            WHEN SERIES=4 AND ORTRXTYP=4 THEN 'Devolucion'
		            WHEN SERIES=4 AND ORTRXTYP=5 THEN 'Devolucion credito'
		            WHEN SERIES=4 AND ORTRXTYP=6 THEN 'Cheques' 
		            WHEN SERIES=5 AND ORTRXTYP=0 THEN 'Entrada de inventario generada por el sistema' 
		            WHEN SERIES=5 AND ORTRXTYP=1 THEN 'Ajuste' 
		            WHEN SERIES=5 AND ORTRXTYP=2 THEN 'Variacion' 
		            WHEN SERIES=5 AND ORTRXTYP=3 THEN 'Transferencia' 
		            ELSE 'Otras Transaccion' END'Tipo_transaccion'
		FROM GL30000 G3 INNER JOIN GL00100 G1 ON G3.ACTINDX=G1.ACTINDX 
WHERE G3.HSTYEAR='2012' AND SERIES=3 AND ORTRXTYP=9--(RTRIM(ACTNUMBR_1)+'-'+RTRIM(ACTNUMBR_2)+'-'+RTRIM(ACTNUMBR_3)) IN ( '00-113020000-00')

)AS A
GROUP BY A.SOURCDOC,
	   A.JRNENTRY,
       A.AÑO,
       A.Series,
       A.CUENTA,
       A.TRXDATE,
	   A.DESCRIPCION,
	   A.REFRENCE,
	   A.DSCRIPTN,
       A.ORCTRNUM,
       A.ORMSTRID,
       A.ORMSTRNM,
       A.Tipo_transaccion,
       A.ORDOCNUM,
       --A.SALDO_INICIAL,
       A.ANULADO
ORDER BY A.JRNENTRY

SELECT  * FROM GL30000
WHERE HSTYEAR='2012' AND SERIES=5 AND ORTRXTYP=3 --AND ORCTRNUM<>'' 
--AND ORMSTRNM<>''
--AND SOURCDOC='DG'
ORDER BY SOURCDOC


SELECT * FROM GL10001


SELECT * FROM GL11111
SELECT ACTINDX,PERDBLNC FROM GL10111
WHERE YEAR1='2012' AND PERIODID=0

SELECT * FROM GL32000
WHERE ACTINDX=39


SELECT * FROM SOP30300
WHERE SOPNUMBE IN (

SELECT SOPNUMBE FROM vw_VentasGP
WHERE DOCDATE BETWEEN '20120101' AND '20121231' AND ITEMNMBR IN ('PT210','PT602','PT110')) AND ITEMNMBR='PT110'
/*
UPDATE SOP30300
SET ITEMDESC='ALASKA, FUNDA DE HIELO REGULAR'
WHERE SOPNUMBE IN (

SELECT SOPNUMBE FROM vw_VentasGP
WHERE DOCDATE BETWEEN '20120101' AND '20121231' AND ITEMNMBR IN ('PT210','PT602','PT110')) AND ITEMNMBR='PT110'*/

--(PT210,PT602,PT110)

SELECT * FROM PalmComSync..IN_FACTURA_TEMP
WHERE FECHAFAC='20141204' AND PALMID='GEA019'

SELECT * FROM PalmComSync..IN_DETAFAC
WHERE FACNUM IN (SELECT FACNUM FROM PalmComSync..IN_FACTURA_TEMP
WHERE FECHAFAC='20141204' AND PALMID='GEA019')

SELECT * FROM SITGPIntegration..TransaccionVenta
WHERE NoDocumento IN (SELECT FACNUM FROM PalmComSync..IN_FACTURA_TEMP
WHERE FECHAFAC='20141204' AND PALMID='GEA019')

SELECT * FROM SITGPIntegration..TransaccionVentaItem
WHERE IDVenta IN (
SELECT IDVenta FROM SITGPIntegration..TransaccionVenta
WHERE NoDocumento IN (SELECT FACNUM FROM PalmComSync..IN_FACTURA_TEMP
WHERE FECHAFAC='20141204' AND PALMID='GEA019'))


SELECT * FROM SOP10200
WHERE SOPNUMBE LIKE '%F0450025584%'



SELECT * FROM GL30000
WHERE SERIES=3 AND ORTRXTYP=9 AND HSTYEAR=2012