create PROCEDURE REPORTE80_20
@IFECHA DATETIME,
@TFECHA DATETIME

AS

declare @VALOR INT

SET @VALOR=(

select SUM(RESULT.TOTAL_VALOR) AS SUMA from (

SELECT 
		SUM(XTNDPRCE)'TOTAL_VALOR' 
	
		,v.CUSTNAME,v.CUSTNMBR
		FROM  PS_vw_VentasGP1   as v with(nolock)
WHERE v.DOCDATE BETWEEN @IFECHA AND @TFECHA AND SOPNUMBE NOT IN (SELECT DOCNUMBR FROM GPHN.dbo.RM20101
WHERE BCHSOURC='Sales Entry' AND VOIDSTTS=1 AND DOCDATE BETWEEN @IFECHA AND @TFECHA AND RMDTYPAL=1)
GROUP BY v.CUSTNMBR,CUSTNAME

UNION ALL

SELECT   SUM(ORTRXAMT) 'TOTAL_VALOR',
					   CUSTNMBR,'' AS CUSTNAME
FROM RM20101 
WHERE DOCDATE BETWEEN @IFECHA AND @TFECHA AND BCHSOURC IN ('XRM_Sales','RM_Sales') AND RMDTYPAL=1
GROUP BY CUSTNMBR
) as RESULT
)





SELECT * FROM (

SELECT 
		SUM(XTNDPRCE)'TOTAL_VALOR' 
	
		,v.CUSTNAME,v.CUSTNMBR
		,((SUM(XTNDPRCE))/@VALOR)*100  AS  [  %]
		FROM  PS_vw_VentasGP1   as v with(nolock)
WHERE v.DOCDATE BETWEEN @IFECHA AND @TFECHA  AND SOPNUMBE NOT IN (SELECT DOCNUMBR FROM GPHN.dbo.RM20101
WHERE BCHSOURC='Sales Entry' AND VOIDSTTS=1 AND DOCDATE BETWEEN @IFECHA AND @TFECHA AND RMDTYPAL=1)
GROUP BY v.CUSTNMBR,CUSTNAME

UNION ALL

SELECT   SUM(ORTRXAMT) 'TOTAL_VALOR',
					   CUSTNMBR,'' AS CUSTNAME,
					   ((SUM(ORTRXAMT))/@VALOR)*100 AS  [  %]
FROM RM20101 
WHERE DOCDATE BETWEEN @IFECHA AND @TFECHA AND BCHSOURC IN ('XRM_Sales','RM_Sales') AND RMDTYPAL=1
GROUP BY CUSTNMBR
) AS REST ORDER BY TOTAL_VALOR DESC



