--PARA SUSTITUTO EN  EL 86 EJECUTAR EL SIGUIENTE CODIGO 
/***BEGIN ****/
use PalmComSync

exec dbo.sp_sustituto2 '5436','5524'
/**END***/


--PARA PASAR LA DATA EN EL 83 EJECUTA EL SIGUIENTE CODIGO 

/***BEGIN*/

USE alaska_pcomdb
EXEC [CARGAR OUTCLIENTE]
--dbo.CARGAR OUTCONFIG
exec [CARGAR OUTPRECIO]
exec [CARGAR OUTPRODUCTO]
--dbo.OUTSECNCF
--dbo.OUTSECUENCI

/**END*/



