
DECLARE @FECHAA DATETIME, @FECHAB DATETIME, @DIAS INT, @CONTADO INT

SET @FECHAA='20150701'
SET @FECHAB='20150715'
SET @CONTADO=1
--Contar las cantidad de dias de un rango de fecha
SET @DIAS =DATEDIFF(day, @FECHAA,@FECHAB)+1;

--CREAR TABLA TEMPORAL Primer Paso 
/*
CREATE TABLE ##FECHA (
	FECHAS DATETIME,
	PORCIENTO VARCHAR(10),
	NOMBREDIA VARCHAR(10)
)*/


INSERT INTO ##FECHA(FECHAS,PORCIENTO, NOMBREDIA)
  SELECT @FECHAA, (CONVERT(VARCHAR(10),CONVERT(MONEY,((@CONTADO*100.0)/@DIAS)))+'%'), DATENAME(weekday,@FECHAA)
	    
	    
WHILE (@FECHAA<@FECHAB)
	BEGIN
		SET @CONTADO=@CONTADO+1
		SET @FECHAA=@FECHAA+1
		INSERT INTO ##FECHA(FECHAS,PORCIENTO, NOMBREDIA)
	     SELECT @FECHAA, (CONVERT(VARCHAR(10),CONVERT(MONEY,((@CONTADO*100.0)/@DIAS)))+'%'), DATENAME(weekday,@FECHAA)
		
		
END

	    
SELECT rank() OVER(ORDER BY FECHAS) as ORDEN
	,FECHAS
	,CONVERT(VARCHAR,	
				CONVERT(MONEY,
							(rank() OVER(ORDER BY FECHAS)*100.0)/(SELECT COUNT(FECHAS)FROM ##FECHA)))+'%' as PORCIENTO
FROM ##FECHA
GROUP BY FECHAS

	    
SELECT*
FROM ##FECHA
--Eliminar Datos 

--DELETE FROM ##FECHA

 --Eliminar Tabla temporal 

--DROP TABLE ##FECHA
 