
SELECT     CASE WHEN pm1.VNDCLSID ='INTERNACIO' THEN 'INTERNACIONAL'
			ELSE 'NACIONAL' END 'CLASE', 
           pm1.VENDORID'Id Proveedor',
           VENDSHNM'Nombre',
           Tipo_Documento,
           DOCNUMBR'Numero Documento',
           DOCAMNT'Monto', 
           pm1.DOCDATE'Fecha',
           pm33.APTODCNM'Documento Aplicado',
           pm33.APFRMAPLYAMT'Monto Aplicado',
           pm33.APTODCDT'Fecha Documento',
           pmInicial.SALDO_INICIAL,
           pmFinal.SALDO_FINAL
FROM (
	 SELECT * FROM 
	 ( SELECT  
	         pm2.VENDORID,
			 pm2.VENDSHNM,
			 pm2.VNDCLSID,
	   CASE pm3.DOCTYPE 
			WHEN 1 THEN 'Factura'
			WHEN 2 THEN 'Cargo Financiero'
			WHEN 3 THEN 'Cargos misceláneos'
			WHEN 4 THEN 'Devolucion'
			WHEN 5 THEN 'Nota de Credito'
			WHEN 6 THEN 'Pagos'
			ELSE 'Otros' END'Tipo_Documento',
		DOCNUMBR,
		DOCAMNT,
		DOCDATE
	
FROM GPHN.dbo.PM30200 pm3 INNER JOIN PM00200 pm2 ON RTRIM(pm3.VENDORID)=RTRIM(pm2.VENDORID) 
WHERE VOIDED=0 AND DOCDATE BETWEEN '20120101' AND '20121231'
UNION ALL

 SELECT pm2.VENDORID,
			 pm2.VENDSHNM,
			 pm2.VNDCLSID,
	   CASE pm3.DOCTYPE 
			WHEN 1 THEN 'Factura'
			WHEN 2 THEN 'Cargo Financiero'
			WHEN 3 THEN 'Cargos misceláneos'
			WHEN 4 THEN 'Devolucion'
			WHEN 5 THEN 'Nota de Credito'
			WHEN 6 THEN 'Pagos'
			ELSE 'Otros' END'Tipo_Documento',
		DOCNUMBR,
		DOCAMNT,
		DOCDATE
		


FROM GPHN.dbo.PM20000 pm3 INNER JOIN PM00200 pm2 ON RTRIM(pm3.VENDORID)=RTRIM(pm2.VENDORID) 
WHERE VOIDED=0 AND DOCDATE BETWEEN '20120101' AND '20121231'
) pm
) pm1 LEFT JOIN (
					SELECT VENDORID,
					       SUM(SALDO_INICIAL)SALDO_INICIAL FROM (
					SELECT VENDORID,
						  
						
						  (SUM(ISNULL(CASE WHEN DOCTYPE=1 THEN DOCAMNT END,0))+ SUM(ISNULL(CASE WHEN DOCTYPE=2 THEN DOCAMNT END,0))+SUM(ISNULL(CASE WHEN DOCTYPE=3 THEN DOCAMNT END,0)))
						     - (SUM(ISNULL(CASE WHEN DOCTYPE=4 THEN DOCAMNT END,0))+SUM(ISNULL(CASE WHEN DOCTYPE=5 THEN DOCAMNT END,0))+SUM(ISNULL(CASE WHEN DOCTYPE=6 THEN DOCAMNT END,0)))'SALDO_INICIAL'

						FROM GPHN.dbo.PM30200 
						WHERE 	VOIDED=0 AND DOCDATE <='20111231'
						GROUP BY VENDORID
						UNION ALL
						SELECT VENDORID,
						  
						
						 
						  (SUM(ISNULL(CASE WHEN DOCTYPE=1 THEN DOCAMNT END,0))+ SUM(ISNULL(CASE WHEN DOCTYPE=2 THEN DOCAMNT END,0))+SUM(ISNULL(CASE WHEN DOCTYPE=3 THEN DOCAMNT END,0)))
						     - (SUM(ISNULL(CASE WHEN DOCTYPE=4 THEN DOCAMNT END,0))+SUM(ISNULL(CASE WHEN DOCTYPE=5 THEN DOCAMNT END,0))+SUM(ISNULL(CASE WHEN DOCTYPE=6 THEN DOCAMNT END,0)))'SALDO_INICIAL'

						FROM GPHN.dbo.PM20000
						WHERE 	VOIDED=0 AND DOCDATE <='20111231'
						GROUP BY VENDORID
				)s GROUP BY VENDORID






                )pmInicial ON RTRIM(pm1.VENDORID)=RTRIM(pmInicial.VENDORID)
 LEFT JOIN (
				SELECT VENDORID, 
				       SUM(SALDO_FINAL)SALDO_FINAL 
			FROM (
					SELECT VENDORID,
					
						 
						  (SUM(ISNULL(CASE WHEN pm3.DOCTYPE=1 THEN DOCAMNT END,0))+ SUM(ISNULL(CASE WHEN pm3.DOCTYPE=2 THEN DOCAMNT END,0))+SUM(ISNULL(CASE WHEN pm3.DOCTYPE=3 THEN DOCAMNT END,0)))
						     - (SUM(ISNULL(CASE WHEN pm3.DOCTYPE=4 THEN DOCAMNT END,0))+SUM(ISNULL(CASE WHEN pm3.DOCTYPE=5 THEN DOCAMNT END,0))+SUM(ISNULL(CASE WHEN pm3.DOCTYPE=6 THEN DOCAMNT END,0)))'SALDO_FINAL'

						FROM GPHN.dbo.PM30200 pm3 --INNER JOIN PM00200 pm2 ON pm3.VENDORID=pm2.VENDORID 
						WHERE 	VOIDED=0 AND DOCDATE <='20121231'
						GROUP BY VENDORID
						UNION 
						SELECT VENDORID,
						  
						 
						 
						  (SUM(ISNULL(CASE WHEN pm3.DOCTYPE=1 THEN DOCAMNT END,0))+ SUM(ISNULL(CASE WHEN pm3.DOCTYPE=2 THEN DOCAMNT END,0))+SUM(ISNULL(CASE WHEN pm3.DOCTYPE=3 THEN DOCAMNT END,0)))
						     - (SUM(ISNULL(CASE WHEN pm3.DOCTYPE=4 THEN DOCAMNT END,0))+SUM(ISNULL(CASE WHEN pm3.DOCTYPE=5 THEN DOCAMNT END,0))+SUM(ISNULL(CASE WHEN pm3.DOCTYPE=6 THEN DOCAMNT END,0)))'SALDO_FINAL'

						FROM GPHN.dbo.PM20000 pm3 --INNER JOIN PM00200 pm2 ON pm3.VENDORID=pm2.VENDORID 
						WHERE 	VOIDED=0 AND DOCDATE <='20121231'
						GROUP BY VENDORID
						
						) s GROUP BY s.VENDORID






                )pmFinal ON RTRIM(pm1.VENDORID)=RTRIM(pmFinal.VENDORID)
 LEFT JOIN 
 PM30300 pm33 ON RTRIM(pm1.DOCNUMBR)=RTRIM(pm33.APFRDCNM) AND RTRIM(pm1.VENDORID)=RTRIM(pm33.VENDORID)

ORDER BY pm1.VENDORID

SELECT VNDCLSID FROM  PM00200
GROUP BY VNDCLSID
 


