create table ##ITEMRESULT
([NUMERO DE ITEM] varchar(40)
,CLASE VARCHAR(13)
,DESCRIPCION VARCHAR(100)
,[UNIDAD DE MEDIDA] VARCHAR(80)
,LOCALIDAD VARCHAR(80)
,COSTO_ACTUAL DECIMAL(18,10)
,[PRECIO EXTENDIDO] DECIMAL(18,10)
,cantidad DECIMAL(18,10)
,DOCUMENT_NUMBER VARCHAR(100)
,IDENTIFICAR VARCHAR (10)
)



INSERT INTO ##ITEMRESULT ([NUMERO DE ITEM],CLASE,DESCRIPCION,[UNIDAD DE MEDIDA],LOCALIDAD,COSTO_ACTUAL,[PRECIO EXTENDIDO],cantidad,DOCUMENT_NUMBER,IDENTIFICAR)


select IV00101.ITEMNMBR AS [NUMERO DE ITEM],IV00101.ITMCLSCD AS CLASE 
,ITEMDESC AS DESCRIPCION,IV00101.SELNGUOM AS [UNIDAD DE MEDIDA] ,'SANISIDRO' AS LOCALIDAD ,IV00101.CURRCOST AS 
COSTO_ACTUAL,IV00101.CURRCOST*IV00102.QTYONHND AS [PRECIO EXTENDIDO], 
QTYONHND AS CANTIDAD,'' AS DOCUMENT_NUMBER ,'HEADER' AS IDENTIFICAR from IV00101 JOIN  iv00102 ON IV00101.ITEMNMBR=IV00102.ITEMNMBR
 where IV00101.ITMCLSCD IN ('IR')--('HT','IB','DETERGENTE','LICORES','IC','IR','IL','ME','MG','MP') 
  and  IV00102.LOCNCODE='SANISIDRO'
 
 union all
 
 select IV00101.ITEMNMBR AS [NUMERO DE ITEM],IV00101.ITMCLSCD 
 AS CLASE,ITEMDESC AS DESCRIPCION ,IV00101.SELNGUOM 
 AS [UNIDAD DE MEDIDA],'SANISIDRO' AS LOCALIDAD,IV00101.CURRCOST 
 AS COSTO_ACTUAL,(IV30300.TRXQTY*-1)*IV00101.CURRCOST 
 AS [PRECIO EXTENDIDO] ,TRXQTY*-1 AS 
 CANTIDAD,IV30300.DOCNUMBR AS DOCUMENT_NUMBER ,'' AS IDENTIFICAR
 FROM GPHN.dbo.IV30300 (nolock) LEFT OUTER JOIN GPHN.dbo.IV00101 (nolock)  ON GPHN.dbo.IV30300.ITEMNMBR = GPHN.dbo.IV00101.ITEMNMBR  LEFT OUTER JOIN GPHN.dbo.IV30200 (nolock) 
  ON GPHN.dbo.IV30300.DOCTYPE = GPHN.dbo.IV30200.IVDOCTYP  AND GPHN.dbo.IV30300.DOCNUMBR = GPHN.dbo.IV30200.DOCNUMBR  LEFT OUTER JOIN GPHN.dbo.IV40201 (nolock)  ON GPHN.dbo.IV00101.UOMSCHDL = GPHN.dbo.IV40201.UOMSCHDL 
   WHERE ((UPPER(ISNULL(GPHN.dbo.iv00101.ITMCLSCD,'')) IN ('IR'))--('HT','IB','DETERGENTE','LICORES','IC','IR','IL','ME','MG','MP')) 
   AND (GPHN.dbo.IV30300.DOCDATE > CONVERT(datetime,'20160630')) AND 
   (UPPER(ISNULL(GPHN.dbo.IV30300.TRXLOCTN,'')) LIKE '%SANISIDRO%')) 
	and IV30300.DOCTYPE<>3
		
  
union all 

 select IV00101.ITEMNMBR AS [NUMERO DE ITEM],IV00101.ITMCLSCD 
 AS CLASE,ITEMDESC AS DESCRIPCION ,IV00101.SELNGUOM 
 AS [UNIDAD DE MEDIDA],'SANISIDRO' AS LOCALIDAD,IV00101.CURRCOST 
 AS COSTO_ACTUAL,
 CASE WHEN TRNSTLOC='SANISIDRO' THEN 
( ABS (IV30300.TRXQTY)*-1)*IV00101.CURRCOST
 ELSE
 
 (abs(IV30300.TRXQTY))*IV00101.CURRCOST 
 END
 AS [PRECIO EXTENDIDO] ,
 case when TRNSTLOC='SANISIDRO' then
 (abs(TRXQTY))*-1
  else 
    ABS(TRXQTY)
   end
AS 
 CANTIDAD
 ,IV30300.DOCNUMBR AS DOCUMENT_NUMBER ,'' AS IDENTIFICAR
 FROM GPHN.dbo.IV30300 (nolock) LEFT OUTER JOIN GPHN.dbo.IV00101 (nolock)  ON GPHN.dbo.IV30300.ITEMNMBR = GPHN.dbo.IV00101.ITEMNMBR  LEFT OUTER JOIN GPHN.dbo.IV30200 (nolock) 
  ON GPHN.dbo.IV30300.DOCTYPE = GPHN.dbo.IV30200.IVDOCTYP  AND GPHN.dbo.IV30300.DOCNUMBR = GPHN.dbo.IV30200.DOCNUMBR  LEFT OUTER JOIN GPHN.dbo.IV40201 (nolock)  ON GPHN.dbo.IV00101.UOMSCHDL = GPHN.dbo.IV40201.UOMSCHDL 
   WHERE ((UPPER(ISNULL(GPHN.dbo.iv00101.ITMCLSCD,'')) IN ('IR')) -- ('HT','IB','DETERGENTE','LICORES','IC','IR','IL','ME','MG','MP')) 
   AND (GPHN.dbo.IV30300.DOCDATE > CONVERT(datetime,'20160630')) AND 
   (UPPER(ISNULL(GPHN.dbo.IV30300.TRXLOCTN,'')) LIKE '%SANISIDRO%' OR IV30300.TRNSTLOC LIKE '%SANISIDRO%')) 
   
   
   
   and IV30300.DOCTYPE=3
		

   SELECT [NUMERO DE ITEM],
   CLASE,DESCRIPCION,[UNIDAD DE MEDIDA],LOCALIDAD,
   COSTO_ACTUAL AS COSTOACTUAL ,SUM([PRECIO EXTENDIDO]) 
   AS PRECIO_EXTENDIDO,SUM(cantidad) AS CANTIDAD 
   FROM ##ITEMRESULT WHERE [PRECIO EXTENDIDO]<>0
   
   AND	CANTIDAD<>0
    GROUP  BY [NUMERO DE ITEM],CLASE,DESCRIPCION,[UNIDAD DE MEDIDA],LOCALIDAD,COSTO_ACTUAL
    ORDER BY [NUMERO DE ITEM]
   

 

DROP TABLE ##ITEMRESULT




 
     
