SELECT RMDTYPAL FROM RM20101 R INNER JOIN RM00101 R1 ON R.CUSTNMBR=R1.CUSTNMBR
WHERE CUSTCLAS='VENDEDOR'
GROUP BY RMDTYPAL
SELECT * FROM GL00100
WHERE ACTINDX=785

SELECT ACTINDX,ACTDESCR FROM GPHN.dbo.GL00100
WHERE ACTDESCR LIKE '%Cobrar%' OR ACTDESCR LIKE '%Efec%'
ORDER BY ACTDESCR

SELECT * FROM RM10101
WHERE DOCNUMBR IN (SELECT DOCNUMBR FROM RM20101 R INNER JOIN RM00101 R1 ON R.CUSTNMBR=R1.CUSTNMBR
WHERE CUSTCLAS='VENDEDOR' AND RMDTYPAL IN (9,7)) AND DSTINDX=2 AND DOCNUMBR='RC01903134'

SELECT * FROM (
 SELECT R1.CUSTCLAS,DOCNUMBR,r.CUSTNMBR,CUSTNAME,SUM(DEBITAMT)'DEBITO',SUM(CRDTAMNT)'CREDITO',ACTDESCR,(RTRIM(ACTNUMBR_1)+'-'+RTRIM(ACTNUMBR_2)+'-'+RTRIM(ACTNUMBR_3))'CUENTA' FROM RM10101 R INNER JOIN RM00101 R1 ON R.CUSTNMBR=R1.CUSTNMBR INNER JOIN GL00100 G ON R.DSTINDX=G.ACTINDX
WHERE CUSTCLAS='VENDEDOR' AND RMDTYPAL IN (9,7) AND  POSTEDDT BETWEEN '20130101' AND '20131231' AND DSTINDX  IN (33,785) 
GROUP BY R1.CUSTCLAS,DOCNUMBR,CUSTNAME,ACTDESCR,(RTRIM(ACTNUMBR_1)+'-'+RTRIM(ACTNUMBR_2)+'-'+RTRIM(ACTNUMBR_3)) ,r.CUSTNMBR
) a --WHERE CREDITO=0

ORDER BY a.DOCNUMBR



SELECT * FROM DataRS..Detalle_cuadre_cajera
WHERE Documento='SANI-00018312'


SELECT * FROM (
 SELECT R1.CUSTCLAS,DOCNUMBR,r.CUSTNMBR,CUSTNAME,SUM(DEBITAMT)'DEBITO',SUM(CRDTAMNT)'CREDITO',ACTDESCR,(RTRIM(ACTNUMBR_1)+'-'+RTRIM(ACTNUMBR_2)+'-'+RTRIM(ACTNUMBR_3))'CUENTA' FROM RM10101 R INNER JOIN RM00101 R1 ON R.CUSTNMBR=R1.CUSTNMBR INNER JOIN GL00100 G ON R.DSTINDX=G.ACTINDX
WHERE CUSTCLAS IN (@CLASE) AND RMDTYPAL IN (@TIPODOC) AND  POSTEDDT BETWEEN @IFECHA AND @AFECHA AND DSTINDX NOT IN (@CUENTA) 
GROUP BY R1.CUSTCLAS,DOCNUMBR,CUSTNAME,ACTDESCR,(RTRIM(ACTNUMBR_1)+'-'+RTRIM(ACTNUMBR_2)+'-'+RTRIM(ACTNUMBR_3)) ,r.CUSTNMBR
) a


SELECT CLASDSCR,CLASSID FROM RM00201
WHERE CLASDSCR<>''
ORDER BY CLASDSCR

SELECT * FROM AAG00401

SELECT * FROM AAG00200