
   SELECT DATASET.SOPNUMBE as [FACTURA],DATASET.ITEMNMBR AS ARTICULO,
   DATASET.UNITPRCE AS PRECIO,DATASET.QUANTITY AS CANTIDAD,DATASET.XTNDPRCE AS MONTO,
   DATASET.DOCDATE AS FECHA,DATASET.Grupo_Trabajo AS GRUPO_DE_TRABAJO,DATASET.Numero AS 
   CODIGO_DE_EMPLEADO,DATASET.Nom_Emp AS NOMBRE_DE_EMPLEADO,
   
 
   CASE WHEN (SELECT COUNT(*) AS RESULT FROM DataRS..CLIENTES_RANCHEROS WHERE CODIGO=DATASET.CUSTNMBR and NombreRuta like '%SD300%')>0 AND DATASET.ITEMNMBR LIKE '%PT100%' THEN [2PORCIENTO] 
   ELSE
   DATASET.[4PORCIENTO]
   END 
   AS COMISION,DATASET.[4PORCIENTO],[2PORCIENTO]
   ,DATASET.CUSTNMBR AS CLIENTE
   FROM (
        select v.SOPNUMBE 
            ,v.ITEMNMBR
            ,v.UNITPRCE
            ,v.QUANTITY
            ,XTNDPRCE
            ,v.DOCDATE
            ,v.CUSTNMBR
            ,e.Grupo_Trabajo
            ,e.Desc_SubGrupo
            ,e.Numero
            ,e.Nom_Emp
            ,
           
            CASE 
      
	    WHEN V.ITEMNMBR = 'PT100' AND V.UNITPRCE <= 31 THEN V.XTNDPRCE * 0.025 
		WHEN V.ITEMNMBR = 'PT100' AND V.UNITPRCE >= 32 THEN V.QUANTITY * 0.775 
		WHEN V.ITEMNMBR = 'PT103' AND V.UNITPRCE <= 31 THEN V.XTNDPRCE * 0.025 
		WHEN V.ITEMNMBR = 'PT103' AND V.UNITPRCE >= 32 THEN V.QUANTITY * 0.775 
		WHEN V.ITEMNMBR = 'PT901' THEN V.QUANTITY * 0.5 

		WHEN V.ITEMNMBR = 'PT200' OR V.ITEMNMBR = 'PT204' THEN V.XTNDPRCE * 0.025 
		WHEN V.ITEMNMBR = 'PT300' THEN V.XTNDPRCE * 0.10 
			--WHEN V.ITEMNMBR = 'PT300' AND V.UNITPRCE <= 27 THEN SUM(V.XTNDPRCE) * 0.10 
			--WHEN V.ITEMNMBR = 'PT300' AND V.UNITPRCE >= 28 THEN SUM(V.QUANTITY) * 2.7 
		
		WHEN V.ITEMNMBR = 'PT400' THEN V.XTNDPRCE * 0.04 
	    WHEN V.ITEMNMBR = 'PT430' THEN V.XTNDPRCE * 0.04 
	    WHEN V.ITEMNMBR = 'PT500' THEN V.XTNDPRCE * 0.04 
        WHEN V.ITEMNMBR = 'PT504' THEN V.XTNDPRCE * 0.04 
		WHEN V.ITEMNMBR = 'PT600' THEN  V.XTNDPRCE * 0.08 
        WHEN V.ITEMNMBR = 'PT900' THEN V.QUANTITY * 0.5 
		WHEN V.ITEMNMBR = 'EMB100' OR  V.ITEMNMBR = 'EMB101' OR  V.ITEMNMBR = 'EMB200' OR V.ITEMNMBR = 'EMB201' THEN V.XTNDPRCE * 0.03 
		WHEN V.ITEMNMBR = 'COMBO-100' OR
           V.ITEMNMBR = 'COMBO-101' OR
                      V.ITEMNMBR = 'COMBO-102' THEN V.XTNDPRCE * 0.0225 ELSE 0 END  as '4PORCIENTO'
                      ,  CASE 
      
	    WHEN V.ITEMNMBR = 'PT100' AND V.UNITPRCE <= 31 THEN V.XTNDPRCE * 0.025 
		WHEN V.ITEMNMBR = 'PT100' AND V.UNITPRCE >= 32 THEN V.QUANTITY * 0.775 
		WHEN V.ITEMNMBR = 'PT103' AND V.UNITPRCE <= 31 THEN V.XTNDPRCE * 0.025 
		WHEN V.ITEMNMBR = 'PT103' AND V.UNITPRCE >= 32 THEN V.QUANTITY * 0.775 
		WHEN V.ITEMNMBR = 'PT901' THEN V.QUANTITY * 0.5 

		WHEN V.ITEMNMBR = 'PT200' OR V.ITEMNMBR = 'PT204' THEN V.XTNDPRCE * 0.025 
		WHEN V.ITEMNMBR = 'PT300' THEN V.XTNDPRCE * 0.10 
			--WHEN V.ITEMNMBR = 'PT300' AND V.UNITPRCE <= 27 THEN SUM(V.XTNDPRCE) * 0.10 
			--WHEN V.ITEMNMBR = 'PT300' AND V.UNITPRCE >= 28 THEN SUM(V.QUANTITY) * 2.7 
		
		WHEN V.ITEMNMBR = 'PT400' THEN V.XTNDPRCE * 0.02 
	    WHEN V.ITEMNMBR = 'PT430' THEN V.XTNDPRCE * 0.02 
	    WHEN V.ITEMNMBR = 'PT500' THEN V.XTNDPRCE * 0.04 
        WHEN V.ITEMNMBR = 'PT504' THEN V.XTNDPRCE * 0.04 
		WHEN V.ITEMNMBR = 'PT600' THEN  V.XTNDPRCE * 0.08 
        WHEN V.ITEMNMBR = 'PT900' THEN V.QUANTITY * 0.5 
		WHEN V.ITEMNMBR = 'EMB100' OR  V.ITEMNMBR = 'EMB101' OR  V.ITEMNMBR = 'EMB200' OR V.ITEMNMBR = 'EMB201' THEN V.XTNDPRCE * 0.03 
		WHEN V.ITEMNMBR = 'COMBO-100' OR
           V.ITEMNMBR = 'COMBO-101' OR
                      V.ITEMNMBR = 'COMBO-102' THEN V.XTNDPRCE * 0.0225 ELSE 0 END  as '2PORCIENTO'
                FROM       vw_VentasGP1 as v
             left JOIN
                      Personal_Nomina.dbo.vw_Empleados AS e ON RTRIM(CASE v.IdVendedor WHEN '0488' THEN '488' ELSE  v.IdVendedor END) = RTRIM(e.Numero)
WHERE     (v.DOCDATE BETWEEN '20170101' AND '20170130') 
--AND (v.ITEMNMBR = 'pt100')
 AND (e.SubGrupo_Trabajo IN ('121', '162','222','291','231')) AND (v.IdVendedor <> 'D001') AND  
                      (v.ITEMNMBR <> 'OT006') AND (v.ITEMNMBR <> 'KIT300')) AS DATASET where 
                      DATASET.UNITPRCE<>0 AND DATASET.QUANTITY<>0 AND DATASET.ITEMNMBR LIKE '%PT100%'
                      
                      ORDER BY DATASET.SOPNUMBE  
                      
                      
                   
                      
                      
                      