SELECT c.IdClase, CUSTNMBR,SOPNUMBE,COUNT(*) OVER (PARTITION BY SOPNUMBE), SUM(QUANTITY)'CANTIDAD',SUM(XTNDPRCE)'MONTO', c.IdZona ,COUNT(*)
FROM dbo.vw_VentasGPconConduceCA1 v INNER JOIN  vw_Clientes_CSR c ON RTRIM(v.CUSTNMBR)=RTRIM(c.CodCliente) 
WHERE  DOCDATE BETWEEN '20151001' AND '20151031' AND DOCID NOT IN( 'A0100800101','A0100800115','A0100800114')  AND ITEMNMBR ='PT100' AND NombreRuta LIKE 'SD100%'
AND UNITPRCE<>0  AND c.IdClase<>'PUESTO DE VENTA' AND CUSTNMBR='50101'
GROUP BY c.IdClase,  CUSTNMBR,c.IdZona,SOPNUMBE




SELECT   c.IdZona , c.IdClase, 
       CUSTNMBR,
      SOPNUMBE,
      
      (( SUM(QUANTITY))/COUNT(*))/  COUNT(SOPNUMBE) OVER (PARTITION BY SOPNUMBE)'CANTIDAD',
       ((SUM(XTNDPRCE))/COUNT(*))/  COUNT(SOPNUMBE) OVER (PARTITION BY SOPNUMBE)'MONTO'
 
      
FROM dbo.vw_VentasGPconConduceCA1 v INNER JOIN  vw_Clientes_CSR c ON RTRIM(v.CUSTNMBR)=RTRIM(c.CodCliente) 
WHERE    DOCDATE BETWEEN '20151001' AND '20151031' AND DOCID NOT IN( 'A0100800101','A0100800115','A0100800114')  AND ITEMNMBR ='PT100' AND NombreRuta LIKE 'SD100%' AND UNITPRCE<>0
         AND c.IdClase<>'PUESTO DE VENTA' --AND CUSTNMBR='32799'
GROUP BY c.IdClase,  CUSTNMBR,c.IdZona,SOPNUMBE,QUANTITY,XTNDPRCE
