USE  GPHN
--Buscar Factura
SELECT * FROM (
SELECT DOCID,SOPNUMBE,DOCDATE 
FROM GPHN..SOP30200


UNION ALL

SELECT DOCID,SOPNUMBE,DOCDATE
FROM GPHN..SOP10100
) A
WHERE A.DOCDATE BETWEEN '20160701' AND '20160731' AND DOCID NOT IN ( 'PALMFACTURA','CONDUCE','CALLS SERVICE','MANUAL','PEDIDO')
ORDER BY SOPNUMBE

 

SELECT * FROM import..[SALTOSJULIO2016]
WHERE SALTOS  NOT IN (
SELECT SOPNUMBE FROM (
SELECT DOCID,SOPNUMBE,DOCDATE 
FROM GPHN..SOP30200 



UNION ALL

SELECT DOCID,SOPNUMBE,DOCDATE
FROM GPHN..SOP10100
 
) A
WHERE A.DOCDATE<>'1900-01-01 00:00:00.000'

)



SELECT R.CPRCSTNM 'Id. Corporacion',
		R.CUSTNMBR'Id. Cliente',
		R.CUSTNAME'Nombre Cliente',
		CUSTCLAS'Clase Cliente', 
		dbo.fn_UltimaFecha(R.CUSTNMBR) as 'Fecha Ultima Factura', 
		LOCNCODE'Localidad Transaccion',
		CNTCPRSN'Persona de Contacto',
		ADDRESS1'Direccion 1',
		ADDRESS2 'Direccion 2',
		ADDRESS3 'Direccion 3',
		CITY'Ciudad',
		STATE'Estado o Provincia',
		PHONE1'Telefono 1',
		PHONE2'Telefono 2',
		PYMTRMID'Condicion Pago',
		PRCLEVEL'Nivel Precio',
		CASE INACTIVE WHEN 0 THEN 'Activo' ELSE 'Inactivo' END 'Inactivo',
		CASE HOLD WHEN 0 THEN 'Habiliato' ELSE 'Suspendido' END 'Estatus',
		CREATDDT 'Fecha Creacion',
		MODIFDT'Fecha Modificacion'  
		

FROM (
SELECT CUSTNMBR, DOCDATE, LOCNCODE
FROM GPHN..SOP30200 
WHERE VOIDSTTS=0 AND SOPTYPE=3


UNION ALL

SELECT CUSTNMBR, DOCDATE, LOCNCODE
FROM GPHN..SOP10100
WHERE VOIDSTTS=0 AND SOPTYPE=3
) A INNER JOIN RM00101 R ON A.CUSTNMBR=R.CUSTNMBR
WHERE A.DOCDATE <= '20150228' AND LOCNCODE='BAVARO' 
GROUP BY CPRCSTNM ,
		R.CUSTNMBR,
		R.CUSTNAME,
		CUSTCLAS, 
		
		LOCNCODE,
		CNTCPRSN,
		ADDRESS1,
		ADDRESS2 ,
		ADDRESS3 ,
		CITY,
		STATE,
		PHONE1,
		PHONE2,
		PYMTRMID,
		PRCLEVEL,
		INACTIVE,
		HOLD,
		CREATDDT ,
		MODIFDT 

ORDER BY  R.CUSTNMBR
		
SELECT * FROM RM00101
WHERE CUSTNMBR IN (SELECT CUSTNMBR FROM vw_VentasGP
					WHERE DOCDATE<='20150228' AND LOCNCODE='BAVARO')




SELECT * FROM (
SELECT SOPNUMBE,DOCAMNT
FROM GPHN..SOP30200
WHERE SOPTYPE=3


UNION ALL

SELECT SOPNUMBE,DOCAMNT
FROM GPHN..SOP10100
WHERE SOPTYPE=3
) A


SELECT * FROM vw_VentasGPFacturaNulas
WHERE DOCDATE BETWEEN '20140101' AND '20141231'

---Todo NCF Emitido
WITH NCF AS ( SELECT 
		 R.TXRGNNUM'RNC', 
		CASE DOCID WHEN 'PALMFACTURA' THEN NCF 
		ELSE 'A0'+SOPNUMBE END'NCF',
		DOCDATE'Fecha',
		XTNDPRCE'Monto',
		REPLACE(R.CUSTNAME,',',' ') 'Nombre',
		LOCNCODE'Localidad',
		SUBSTRING(CASE DOCID WHEN 'PALMFACTURA' THEN NCF 
		ELSE 'A0'+SOPNUMBE END,10,2)TipoNCF
		
FROM  dbo.vw_VentasGPFacturaNulas  v INNER JOIN RM00101 R ON v.CUSTNMBR=R.CUSTNMBR
WHERE DOCDATE BETWEEN '20140101' AND '20141231' 
) 
SELECT * FROM NCF



SELECT * FROM PalmComSync..OUT_SECNCF
WHERE PALMID='GEA080'

SELECT * FROM PalmComSync..IN_FACTURA_TEMP
WHERE NoDocumento = '000000000117444'


SELECT * FROM PalmComSync..OUT_CLIENTES
WHERE CODCLIE='40532'


SELECT * FROm SITGPIntegration..RelacionConduce
WHERE NoDocumento='000000000117433'

--INSERT INTO PalmComSync..IN_FACTURA
SELECT * FROM PalmComSync..IN_FACTURA_TEMP
WHERE FECHAFAC='2015-10-06' AND PALMID='GEA028'
ORDER BY FACNUM


SELECT * FROM SITGPIntegration..TransaccionVenta
WHERE NoDocumento IN(
SELECT FACNUM FROM PalmComSync..IN_FACTURA_TEMP
WHERE FECHAFAC='2015-10-06' AND PALMID='GEA028'
 )
 ORDER BY NoDocumento
 
 SELECT * FROM SITGPIntegration..TransaccionVentaItem
 WHERE IDVenta IN (SELECT IDVenta FROM SITGPIntegration..TransaccionVenta
WHERE NoDocumento IN(
SELECT FACNUM FROM PalmComSync..IN_FACTURA_TEMP
WHERE FECHAFAC='2015-10-06' AND PALMID='GEA028'
 ))
 
 SELECT *
 FROM PalmComSync..OUT_CONFIG
 WHERE DIRECCION IN ( 'AUT. SAN ISIDRO')   AND PALMID LIKE 'GEA%'
 


 
 SELECT * FROM PalmComSync.dbo.CF_LOCALIDAD
 
 SELECT C.INIFAC'CF INIFAC',
		C.TIPODOC'CF TIPODOC',
		C.ININCF'CF ININCF',
		O.PALMID'CF OUT PALMID',
		O1.ININCF'SEC NCF',
		O1.TIPODOC,
		O.INIFAC
 FROM PalmComSync.dbo.CF_PUNTOPREFIJO C INNER JOIN PalmComSync..OUT_CONFIG O ON C.INIFAC=O.INIFAC
 INNER JOIN PalmComSync..OUT_SECNCF O1 ON O.PALMID=O1.PALMID AND C.TIPODOC=O1.TIPODOC
 
 
 
 SELECT *
 FROM PalmComSync.dbo.CF_PUNTOPREFIJO

SELECT * FROM SITGPIntegration..RelacionConduce
WHERE NoDocumento='000000000117205'
 
 
 
 
 
SELECT  * FROM (
SELECT DOCID,SOPNUMBE,DOCDATE, 'SOP10100' AS TABLA
FROM GPHN..SOP30200


UNION ALL

SELECT DOCID,SOPNUMBE,DOCDATE, 'SOP10100' AS TABLA
FROM GPHN..SOP10100
) A  
WHERE  SOPNUMBE IN (SELECT FACTURA FROM import..[SALTOSNOVIEMBRE2015]
WHERE FACTURA  NOT IN (
SELECT SOPNUMBE FROM (
SELECT DOCID,SOPNUMBE,DOCDATE 
FROM GPHN..SOP30200 



UNION ALL

SELECT DOCID,SOPNUMBE,DOCDATE
FROM GPHN..SOP10100
 
) A
WHERE A.DOCDATE<>'1900-01-01 00:00:00.000'

))
/*DOCDATE	SALTOS
1/11/2016	10080020100329872
1/31/2016	10080020100332034
1/23/2016	10080020100331120
1/31/2016	10080020100331880
1/29/2016	10080020100331674
*/

SELECT * FROM GPHN..SOP10100
WHERE DOCDATE='1900-01-01 00:00:00.000' 
/*
DELETE FROM GPHN..SOP10100
WHERE DOCDATE='1900-01-01 00:00:00.000'*/


---10080020100316758


SELECT * FROM GPHN..IVC30100
 

SELECT MAX(DOCNUMBR) FROM RM00401
WHERE DOCNUMBR LIKE 'SANI%'   
SELECT * FROM PalmComSync..OUT_PRODUCTO
WHERE PALMID IN (
SELECT PALMID FROM PalmComSync..OUT_CONFIG
WHERE DIRECCION LIKE '%ROMANA%'
)



SELECT * FROM GPHN.dbo.SY03900