
SELECT * FROM SITGPIntegration..RelacionConduce
WHERE Fecha='20160314' AND TipoDocumento='Conduce' AND IdVendedor ='3271'
ORDER BY IdVendedor



SELECT COUNT(ORDDOCID)CANT_COND,ITEMNMBR,SUM([1])'C1',SUM([2])'C2' FROM (
SELECT a.ORDDOCID,
       a.ITEMNMBR,
     
       ISNULL(CASE WHEN RANK() OVER (ORDER BY a.ORDDOCID)=1 THEN a.TRNSFQTY END,0)'1', 
       ISNULL(CASE WHEN RANK() OVER (ORDER BY a.ORDDOCID)=2 THEN a.TRNSFQTY END,0)'2' 
FROM (
SELECT ORDDOCID,ITEMNMBR,TRNSFQTY FROM GPHN.dbo.SVC30701 
--WHERE ORDDOCID = '000000000156522' 
UNION ALL
SELECT ORDDOCID,ITEMNMBR,TRNSFQTY  FROM SVC00701
--WHERE ORDDOCID = '000000000156522'
 
) a	
  WHERE a.ORDDOCID IN (SELECT NoDocumento FROM SITGPIntegration..RelacionConduce
  WHERE Fecha='20160314' AND TipoDocumento='Conduce' AND IdVendedor ='3271'
) AND a.ITEMNMBR='PT100'
GROUP BY a.ITEMNMBR,a.ORDDOCID,a.TRNSFQTY ) b
GROUP BY ITEMNMBR