--delete GPHN..CANTIDADES_LIMITE_PROMOCION WHERE DEXROWID='' and CODIGO_TRANSACTION=''

select * from GPHN..LIMITE_PROMOCION WHERE CODIGO in ('34333'

--delete GPHN..CANTIDADES_LIMITE_PROMOCION where DEXROWID>1 and CANTIDAD_DE_ARTICULOS='8499'
delete GPHN..CANTIDADES_LIMITE_PROMOCION where DEXROWID>1 and CANTIDAD_DE_ARTICULOS='8499'

select CODIGO_CLIENTE , SUM(CANTIDAD_DE_ARTICULOS) AS SUMA from GPHN..CANTIDADES_LIMITE_PROMOCION WHERE FECHA>'2017-05-01 00:00:00.000' group by CODIGO_CLIENTE 
SELECT * FROM GPHN..CANTIDADES_LIMITE_PROMOCION

SELECT * FROM GPHN..SalesLineItems
--select GETDATE()
--exec GPHN..CANTIDAD_PT100_VENDIDO 21322
	
--SELECT COUNT(*) AS RESULTADO FROM [GPHN].[dbo].[CANTIDADES_LIMITE_PROMOCION] WHERE [DEXROWID]='32768' and NO_DOCUMENTO='10080020100362299'