


SELECT A.SOPTYPE, A.DOCID, A.SOPNUMBE, A.DOCDATE, A.PRCLEVEL, A.LOCNCODE, A.BACHNUMB, A.CUSTNMBR, A.CUSTNAME, A.PICTICNU, A.VOIDSTTS, A.SLPRSNID, B.ITEMNMBR, B.ITEMDESC, B.QUANTITY, B.UNITPRCE, B.XTNDPRCE  FROM SOP30200 A JOIN SOP30300 B
ON A.SOPNUMBE = B.SOPNUMBE JOIN RM20101 C ON A.SOPNUMBE = C.DOCNUMBR
WHERE A.LOCNCODE = 'BAVARO' AND A.DOCDATE BETWEEN '2014.01.01' AND '2016.07.31' AND B.ITEMNMBR = 'PT300' AND A.VOIDSTTS = '0' AND C.VOIDSTTS = '0'